// Code generated by protoc-gen-go-json. DO NOT EDIT.
// versions:
// - protoc-gen-go-json vmaster
// - protoc             v3.9.1
// source: lorawan-stack/api/applicationserver_pubsub.proto

package ttnpb

import (
	gogo "github.com/TheThingsIndustries/protoc-gen-go-json/gogo"
	jsonplugin "github.com/TheThingsIndustries/protoc-gen-go-json/jsonplugin"
)

// MarshalProtoJSON marshals the ApplicationPubSub_MQTTProvider_QoS to JSON.
func (x ApplicationPubSub_MQTTProvider_QoS) MarshalProtoJSON(s *jsonplugin.MarshalState) {
	s.WriteEnumString(int32(x), ApplicationPubSub_MQTTProvider_QoS_name)
}

// UnmarshalProtoJSON unmarshals the ApplicationPubSub_MQTTProvider_QoS from JSON.
func (x *ApplicationPubSub_MQTTProvider_QoS) UnmarshalProtoJSON(s *jsonplugin.UnmarshalState) {
	v := s.ReadEnum(ApplicationPubSub_MQTTProvider_QoS_value)
	if err := s.Err(); err != nil {
		s.SetErrorf("could not read QoS enum: %v", err)
		return
	}
	*x = ApplicationPubSub_MQTTProvider_QoS(v)
}

// MarshalProtoJSON marshals the ApplicationPubSub_MQTTProvider message to JSON.
func (x *ApplicationPubSub_MQTTProvider) MarshalProtoJSON(s *jsonplugin.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.ServerUrl != "" {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("server_url")
		s.WriteString(x.ServerUrl)
	}
	if x.ClientId != "" {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("client_id")
		s.WriteString(x.ClientId)
	}
	if x.Username != "" {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("username")
		s.WriteString(x.Username)
	}
	if x.Password != "" {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("password")
		s.WriteString(x.Password)
	}
	if x.SubscribeQos != 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("subscribe_qos")
		x.SubscribeQos.MarshalProtoJSON(s)
	}
	if x.PublishQos != 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("publish_qos")
		x.PublishQos.MarshalProtoJSON(s)
	}
	if x.UseTls {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("use_tls")
		s.WriteBool(x.UseTls)
	}
	if len(x.TlsCa) > 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("tls_ca")
		s.WriteBytes(x.TlsCa)
	}
	if len(x.TlsClientCert) > 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("tls_client_cert")
		s.WriteBytes(x.TlsClientCert)
	}
	if len(x.TlsClientKey) > 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("tls_client_key")
		s.WriteBytes(x.TlsClientKey)
	}
	if x.Headers != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("headers")
		s.WriteObjectStart()
		var wroteElement bool
		for k, v := range x.Headers {
			s.WriteMoreIf(&wroteElement)
			s.WriteObjectStringField(k)
			s.WriteString(v)
		}
		s.WriteObjectEnd()
	}
	s.WriteObjectEnd()
}

// UnmarshalProtoJSON unmarshals the ApplicationPubSub_MQTTProvider message from JSON.
func (x *ApplicationPubSub_MQTTProvider) UnmarshalProtoJSON(s *jsonplugin.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.ReadAny() // ignore unknown field
		case "server_url", "serverUrl":
			x.ServerUrl = s.ReadString()
		case "client_id", "clientId":
			x.ClientId = s.ReadString()
		case "username":
			x.Username = s.ReadString()
		case "password":
			x.Password = s.ReadString()
		case "subscribe_qos", "subscribeQos":
			x.SubscribeQos.UnmarshalProtoJSON(s)
		case "publish_qos", "publishQos":
			x.PublishQos.UnmarshalProtoJSON(s)
		case "use_tls", "useTls":
			x.UseTls = s.ReadBool()
		case "tls_ca", "tlsCa":
			x.TlsCa = s.ReadBytes()
		case "tls_client_cert", "tlsClientCert":
			x.TlsClientCert = s.ReadBytes()
		case "tls_client_key", "tlsClientKey":
			x.TlsClientKey = s.ReadBytes()
		case "headers":
			x.Headers = make(map[string]string)
			s.ReadStringMap(func(key string) {
				x.Headers[key] = s.ReadString()
			})
		}
	})
}

// MarshalProtoJSON marshals the ApplicationPubSub message to JSON.
func (x *ApplicationPubSub) MarshalProtoJSON(s *jsonplugin.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if true { // (gogoproto.nullable) = false
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("ids")
		// NOTE: ApplicationPubSubIdentifiers does not seem to implement MarshalProtoJSON.
		gogo.MarshalMessage(s, &x.ApplicationPubSubIdentifiers)
	}
	if true { // (gogoproto.nullable) = false
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("created_at")
		s.WriteTime(x.CreatedAt)
	}
	if true { // (gogoproto.nullable) = false
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("updated_at")
		s.WriteTime(x.UpdatedAt)
	}
	if x.Format != "" {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("format")
		s.WriteString(x.Format)
	}
	if x.Provider != nil {
		switch v := x.Provider.(type) {
		case *ApplicationPubSub_Nats:
			s.WriteMoreIf(&wroteField)
			s.WriteObjectField("nats")
			// NOTE: ApplicationPubSub_NATSProvider does not seem to implement MarshalProtoJSON.
			gogo.MarshalMessage(s, v.Nats)
		case *ApplicationPubSub_Mqtt:
			s.WriteMoreIf(&wroteField)
			s.WriteObjectField("mqtt")
			v.Mqtt.MarshalProtoJSON(s.WithField("mqtt"))
		case *ApplicationPubSub_AwsIot:
			s.WriteMoreIf(&wroteField)
			s.WriteObjectField("aws_iot")
			// NOTE: ApplicationPubSub_AWSIoTProvider does not seem to implement MarshalProtoJSON.
			gogo.MarshalMessage(s, v.AwsIot)
		}
	}
	if x.BaseTopic != "" {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("base_topic")
		s.WriteString(x.BaseTopic)
	}
	if x.DownlinkPush != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("downlink_push")
		// NOTE: ApplicationPubSub_Message does not seem to implement MarshalProtoJSON.
		gogo.MarshalMessage(s, x.DownlinkPush)
	}
	if x.DownlinkReplace != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("downlink_replace")
		// NOTE: ApplicationPubSub_Message does not seem to implement MarshalProtoJSON.
		gogo.MarshalMessage(s, x.DownlinkReplace)
	}
	if x.UplinkMessage != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("uplink_message")
		// NOTE: ApplicationPubSub_Message does not seem to implement MarshalProtoJSON.
		gogo.MarshalMessage(s, x.UplinkMessage)
	}
	if x.JoinAccept != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("join_accept")
		// NOTE: ApplicationPubSub_Message does not seem to implement MarshalProtoJSON.
		gogo.MarshalMessage(s, x.JoinAccept)
	}
	if x.DownlinkAck != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("downlink_ack")
		// NOTE: ApplicationPubSub_Message does not seem to implement MarshalProtoJSON.
		gogo.MarshalMessage(s, x.DownlinkAck)
	}
	if x.DownlinkNack != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("downlink_nack")
		// NOTE: ApplicationPubSub_Message does not seem to implement MarshalProtoJSON.
		gogo.MarshalMessage(s, x.DownlinkNack)
	}
	if x.DownlinkSent != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("downlink_sent")
		// NOTE: ApplicationPubSub_Message does not seem to implement MarshalProtoJSON.
		gogo.MarshalMessage(s, x.DownlinkSent)
	}
	if x.DownlinkFailed != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("downlink_failed")
		// NOTE: ApplicationPubSub_Message does not seem to implement MarshalProtoJSON.
		gogo.MarshalMessage(s, x.DownlinkFailed)
	}
	if x.DownlinkQueued != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("downlink_queued")
		// NOTE: ApplicationPubSub_Message does not seem to implement MarshalProtoJSON.
		gogo.MarshalMessage(s, x.DownlinkQueued)
	}
	if x.DownlinkQueueInvalidated != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("downlink_queue_invalidated")
		// NOTE: ApplicationPubSub_Message does not seem to implement MarshalProtoJSON.
		gogo.MarshalMessage(s, x.DownlinkQueueInvalidated)
	}
	if x.LocationSolved != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("location_solved")
		// NOTE: ApplicationPubSub_Message does not seem to implement MarshalProtoJSON.
		gogo.MarshalMessage(s, x.LocationSolved)
	}
	if x.ServiceData != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("service_data")
		// NOTE: ApplicationPubSub_Message does not seem to implement MarshalProtoJSON.
		gogo.MarshalMessage(s, x.ServiceData)
	}
	s.WriteObjectEnd()
}

// UnmarshalProtoJSON unmarshals the ApplicationPubSub message from JSON.
func (x *ApplicationPubSub) UnmarshalProtoJSON(s *jsonplugin.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.ReadAny() // ignore unknown field
		case "ids":
			// NOTE: ApplicationPubSubIdentifiers does not seem to implement UnmarshalProtoJSON.
			var v ApplicationPubSubIdentifiers
			gogo.UnmarshalMessage(s, &v)
			x.ApplicationPubSubIdentifiers = v
		case "created_at", "createdAt":
			v := s.ReadTime()
			if s.Err() != nil {
				return
			}
			x.CreatedAt = *v
		case "updated_at", "updatedAt":
			v := s.ReadTime()
			if s.Err() != nil {
				return
			}
			x.UpdatedAt = *v
		case "format":
			x.Format = s.ReadString()
		case "nats":
			ov := &ApplicationPubSub_Nats{}
			// NOTE: ApplicationPubSub_NATSProvider does not seem to implement UnmarshalProtoJSON.
			var v ApplicationPubSub_NATSProvider
			gogo.UnmarshalMessage(s, &v)
			ov.Nats = &v
			x.Provider = ov
		case "mqtt":
			ov := &ApplicationPubSub_Mqtt{}
			if !s.ReadNil() {
				ov.Mqtt = &ApplicationPubSub_MQTTProvider{}
				ov.Mqtt.UnmarshalProtoJSON(s.WithField("mqtt"))
			}
			x.Provider = ov
		case "aws_iot", "awsIot":
			ov := &ApplicationPubSub_AwsIot{}
			// NOTE: ApplicationPubSub_AWSIoTProvider does not seem to implement UnmarshalProtoJSON.
			var v ApplicationPubSub_AWSIoTProvider
			gogo.UnmarshalMessage(s, &v)
			ov.AwsIot = &v
			x.Provider = ov
		case "base_topic", "baseTopic":
			x.BaseTopic = s.ReadString()
		case "downlink_push", "downlinkPush":
			// NOTE: ApplicationPubSub_Message does not seem to implement UnmarshalProtoJSON.
			var v ApplicationPubSub_Message
			gogo.UnmarshalMessage(s, &v)
			x.DownlinkPush = &v
		case "downlink_replace", "downlinkReplace":
			// NOTE: ApplicationPubSub_Message does not seem to implement UnmarshalProtoJSON.
			var v ApplicationPubSub_Message
			gogo.UnmarshalMessage(s, &v)
			x.DownlinkReplace = &v
		case "uplink_message", "uplinkMessage":
			// NOTE: ApplicationPubSub_Message does not seem to implement UnmarshalProtoJSON.
			var v ApplicationPubSub_Message
			gogo.UnmarshalMessage(s, &v)
			x.UplinkMessage = &v
		case "join_accept", "joinAccept":
			// NOTE: ApplicationPubSub_Message does not seem to implement UnmarshalProtoJSON.
			var v ApplicationPubSub_Message
			gogo.UnmarshalMessage(s, &v)
			x.JoinAccept = &v
		case "downlink_ack", "downlinkAck":
			// NOTE: ApplicationPubSub_Message does not seem to implement UnmarshalProtoJSON.
			var v ApplicationPubSub_Message
			gogo.UnmarshalMessage(s, &v)
			x.DownlinkAck = &v
		case "downlink_nack", "downlinkNack":
			// NOTE: ApplicationPubSub_Message does not seem to implement UnmarshalProtoJSON.
			var v ApplicationPubSub_Message
			gogo.UnmarshalMessage(s, &v)
			x.DownlinkNack = &v
		case "downlink_sent", "downlinkSent":
			// NOTE: ApplicationPubSub_Message does not seem to implement UnmarshalProtoJSON.
			var v ApplicationPubSub_Message
			gogo.UnmarshalMessage(s, &v)
			x.DownlinkSent = &v
		case "downlink_failed", "downlinkFailed":
			// NOTE: ApplicationPubSub_Message does not seem to implement UnmarshalProtoJSON.
			var v ApplicationPubSub_Message
			gogo.UnmarshalMessage(s, &v)
			x.DownlinkFailed = &v
		case "downlink_queued", "downlinkQueued":
			// NOTE: ApplicationPubSub_Message does not seem to implement UnmarshalProtoJSON.
			var v ApplicationPubSub_Message
			gogo.UnmarshalMessage(s, &v)
			x.DownlinkQueued = &v
		case "downlink_queue_invalidated", "downlinkQueueInvalidated":
			// NOTE: ApplicationPubSub_Message does not seem to implement UnmarshalProtoJSON.
			var v ApplicationPubSub_Message
			gogo.UnmarshalMessage(s, &v)
			x.DownlinkQueueInvalidated = &v
		case "location_solved", "locationSolved":
			// NOTE: ApplicationPubSub_Message does not seem to implement UnmarshalProtoJSON.
			var v ApplicationPubSub_Message
			gogo.UnmarshalMessage(s, &v)
			x.LocationSolved = &v
		case "service_data", "serviceData":
			// NOTE: ApplicationPubSub_Message does not seem to implement UnmarshalProtoJSON.
			var v ApplicationPubSub_Message
			gogo.UnmarshalMessage(s, &v)
			x.ServiceData = &v
		}
	})
}

// MarshalProtoJSON marshals the ApplicationPubSubs message to JSON.
func (x *ApplicationPubSubs) MarshalProtoJSON(s *jsonplugin.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if len(x.Pubsubs) > 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("pubsubs")
		s.WriteArrayStart()
		var wroteElement bool
		for _, element := range x.Pubsubs {
			s.WriteMoreIf(&wroteElement)
			element.MarshalProtoJSON(s.WithField("pubsubs"))
		}
		s.WriteArrayEnd()
	}
	s.WriteObjectEnd()
}

// UnmarshalProtoJSON unmarshals the ApplicationPubSubs message from JSON.
func (x *ApplicationPubSubs) UnmarshalProtoJSON(s *jsonplugin.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.ReadAny() // ignore unknown field
		case "pubsubs":
			s.ReadArray(func() {
				if !s.ReadNil() {
					v := &ApplicationPubSub{}
					v.UnmarshalProtoJSON(s.WithField("pubsubs"))
					x.Pubsubs = append(x.Pubsubs, v)
				} else {
					x.Pubsubs = append(x.Pubsubs, nil)
				}
			})
		}
	})
}

// MarshalProtoJSON marshals the SetApplicationPubSubRequest message to JSON.
func (x *SetApplicationPubSubRequest) MarshalProtoJSON(s *jsonplugin.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if true { // (gogoproto.nullable) = false
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("pubsub")
		x.ApplicationPubSub.MarshalProtoJSON(s.WithField("pubsub"))
	}
	if x.FieldMask != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("field_mask")
		gogo.MarshalFieldMask(s, x.FieldMask)
	}
	s.WriteObjectEnd()
}

// UnmarshalProtoJSON unmarshals the SetApplicationPubSubRequest message from JSON.
func (x *SetApplicationPubSubRequest) UnmarshalProtoJSON(s *jsonplugin.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.ReadAny() // ignore unknown field
		case "pubsub":
			if !s.ReadNil() {
				x.ApplicationPubSub.UnmarshalProtoJSON(s.WithField("pubsub"))
			}
		case "field_mask", "fieldMask":
			v := gogo.UnmarshalFieldMask(s)
			if s.Err() != nil {
				return
			}
			x.FieldMask = v
		}
	})
}
