// Code generated by protoc-gen-go-json. DO NOT EDIT.
// versions:
// - protoc-gen-go-json vmaster
// - protoc             v3.9.1
// source: lorawan-stack/api/events.proto

package ttnpb

import (
	gogo "github.com/TheThingsIndustries/protoc-gen-go-json/gogo"
	jsonplugin "github.com/TheThingsIndustries/protoc-gen-go-json/jsonplugin"
)

// MarshalProtoJSON marshals the Event message to JSON.
func (x *Event) MarshalProtoJSON(s *jsonplugin.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Name != "" {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("name")
		s.WriteString(x.Name)
	}
	if true { // (gogoproto.nullable) = false
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("time")
		s.WriteTime(x.Time)
	}
	if len(x.Identifiers) > 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("identifiers")
		s.WriteArrayStart()
		var wroteElement bool
		for _, element := range x.Identifiers {
			s.WriteMoreIf(&wroteElement)
			// NOTE: EntityIdentifiers does not seem to implement MarshalProtoJSON.
			gogo.MarshalMessage(s, element)
		}
		s.WriteArrayEnd()
	}
	if x.Data != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("data")
		gogo.MarshalAny(s, x.Data)
	}
	if len(x.CorrelationIds) > 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("correlation_ids")
		s.WriteStringArray(x.CorrelationIds)
	}
	if x.Origin != "" {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("origin")
		s.WriteString(x.Origin)
	}
	if x.Context != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("context")
		s.WriteObjectStart()
		var wroteElement bool
		for k, v := range x.Context {
			s.WriteMoreIf(&wroteElement)
			s.WriteObjectStringField(k)
			s.WriteBytes(v)
		}
		s.WriteObjectEnd()
	}
	if x.Visibility != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("visibility")
		x.Visibility.MarshalProtoJSON(s.WithField("visibility"))
	}
	if x.Authentication != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("authentication")
		// NOTE: Event_Authentication does not seem to implement MarshalProtoJSON.
		gogo.MarshalMessage(s, x.Authentication)
	}
	if x.RemoteIp != "" {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("remote_ip")
		s.WriteString(x.RemoteIp)
	}
	if x.UserAgent != "" {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("user_agent")
		s.WriteString(x.UserAgent)
	}
	if x.UniqueId != "" {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("unique_id")
		s.WriteString(x.UniqueId)
	}
	s.WriteObjectEnd()
}

// UnmarshalProtoJSON unmarshals the Event message from JSON.
func (x *Event) UnmarshalProtoJSON(s *jsonplugin.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.ReadAny() // ignore unknown field
		case "name":
			x.Name = s.ReadString()
		case "time":
			v := s.ReadTime()
			if s.Err() != nil {
				return
			}
			x.Time = *v
		case "identifiers":
			s.ReadArray(func() {
				// NOTE: EntityIdentifiers does not seem to implement UnmarshalProtoJSON.
				var v EntityIdentifiers
				gogo.UnmarshalMessage(s, &v)
				x.Identifiers = append(x.Identifiers, &v)
			})
		case "data":
			v := gogo.UnmarshalAny(s)
			if s.Err() != nil {
				return
			}
			x.Data = v
		case "correlation_ids", "correlationIds":
			x.CorrelationIds = s.ReadStringArray()
		case "origin":
			x.Origin = s.ReadString()
		case "context":
			x.Context = make(map[string][]byte)
			s.ReadStringMap(func(key string) {
				x.Context[key] = s.ReadBytes()
			})
		case "visibility":
			if !s.ReadNil() {
				x.Visibility = &Rights{}
				x.Visibility.UnmarshalProtoJSON(s.WithField("visibility"))
			}
		case "authentication":
			// NOTE: Event_Authentication does not seem to implement UnmarshalProtoJSON.
			var v Event_Authentication
			gogo.UnmarshalMessage(s, &v)
			x.Authentication = &v
		case "remote_ip", "remoteIp":
			x.RemoteIp = s.ReadString()
		case "user_agent", "userAgent":
			x.UserAgent = s.ReadString()
		case "unique_id", "uniqueId":
			x.UniqueId = s.ReadString()
		}
	})
}

// MarshalProtoJSON marshals the FindRelatedEventsResponse message to JSON.
func (x *FindRelatedEventsResponse) MarshalProtoJSON(s *jsonplugin.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if len(x.Events) > 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("events")
		s.WriteArrayStart()
		var wroteElement bool
		for _, element := range x.Events {
			s.WriteMoreIf(&wroteElement)
			element.MarshalProtoJSON(s.WithField("events"))
		}
		s.WriteArrayEnd()
	}
	s.WriteObjectEnd()
}

// UnmarshalProtoJSON unmarshals the FindRelatedEventsResponse message from JSON.
func (x *FindRelatedEventsResponse) UnmarshalProtoJSON(s *jsonplugin.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.ReadAny() // ignore unknown field
		case "events":
			s.ReadArray(func() {
				if !s.ReadNil() {
					v := &Event{}
					v.UnmarshalProtoJSON(s.WithField("events"))
					x.Events = append(x.Events, v)
				} else {
					x.Events = append(x.Events, nil)
				}
			})
		}
	})
}
