// Code generated by protoc-gen-go-json. DO NOT EDIT.
// versions:
// - protoc-gen-go-json vmaster
// - protoc             v3.9.1
// source: lorawan-stack/api/joinserver.proto

package ttnpb

import (
	gogo "github.com/TheThingsIndustries/protoc-gen-go-json/gogo"
	jsonplugin "github.com/TheThingsIndustries/protoc-gen-go-json/jsonplugin"
)

// MarshalProtoJSON marshals the CryptoServicePayloadRequest message to JSON.
func (x *CryptoServicePayloadRequest) MarshalProtoJSON(s *jsonplugin.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if true { // (gogoproto.nullable) = false
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("ids")
		// NOTE: EndDeviceIdentifiers does not seem to implement MarshalProtoJSON.
		gogo.MarshalMessage(s, &x.EndDeviceIdentifiers)
	}
	if x.LorawanVersion != 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("lorawan_version")
		x.LorawanVersion.MarshalProtoJSON(s)
	}
	if len(x.Payload) > 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("payload")
		s.WriteBytes(x.Payload)
	}
	if x.ProvisionerId != "" {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("provisioner_id")
		s.WriteString(x.ProvisionerId)
	}
	if x.ProvisioningData != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("provisioning_data")
		gogo.MarshalStruct(s, x.ProvisioningData)
	}
	s.WriteObjectEnd()
}

// UnmarshalProtoJSON unmarshals the CryptoServicePayloadRequest message from JSON.
func (x *CryptoServicePayloadRequest) UnmarshalProtoJSON(s *jsonplugin.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.ReadAny() // ignore unknown field
		case "ids":
			// NOTE: EndDeviceIdentifiers does not seem to implement UnmarshalProtoJSON.
			var v EndDeviceIdentifiers
			gogo.UnmarshalMessage(s, &v)
			x.EndDeviceIdentifiers = v
		case "lorawan_version", "lorawanVersion":
			x.LorawanVersion.UnmarshalProtoJSON(s)
		case "payload":
			x.Payload = s.ReadBytes()
		case "provisioner_id", "provisionerId":
			x.ProvisionerId = s.ReadString()
		case "provisioning_data", "provisioningData":
			v := gogo.UnmarshalStruct(s)
			if s.Err() != nil {
				return
			}
			x.ProvisioningData = v
		}
	})
}

// MarshalProtoJSON marshals the JoinAcceptMICRequest message to JSON.
func (x *JoinAcceptMICRequest) MarshalProtoJSON(s *jsonplugin.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if true { // (gogoproto.nullable) = false
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("payload_request")
		x.CryptoServicePayloadRequest.MarshalProtoJSON(s.WithField("payload_request"))
	}
	if x.JoinRequestType != 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("join_request_type")
		x.JoinRequestType.MarshalProtoJSON(s)
	}
	if len(x.DevNonce) > 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("dev_nonce")
		x.DevNonce.MarshalProtoJSON(s.WithField("dev_nonce"))
	}
	s.WriteObjectEnd()
}

// UnmarshalProtoJSON unmarshals the JoinAcceptMICRequest message from JSON.
func (x *JoinAcceptMICRequest) UnmarshalProtoJSON(s *jsonplugin.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.ReadAny() // ignore unknown field
		case "payload_request", "payloadRequest":
			if !s.ReadNil() {
				x.CryptoServicePayloadRequest.UnmarshalProtoJSON(s.WithField("payload_request"))
			}
		case "join_request_type", "joinRequestType":
			x.JoinRequestType.UnmarshalProtoJSON(s)
		case "dev_nonce", "devNonce":
			x.DevNonce.UnmarshalProtoJSON(s.WithField("dev_nonce"))
		}
	})
}

// MarshalProtoJSON marshals the DeriveSessionKeysRequest message to JSON.
func (x *DeriveSessionKeysRequest) MarshalProtoJSON(s *jsonplugin.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if true { // (gogoproto.nullable) = false
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("ids")
		// NOTE: EndDeviceIdentifiers does not seem to implement MarshalProtoJSON.
		gogo.MarshalMessage(s, &x.EndDeviceIdentifiers)
	}
	if x.LorawanVersion != 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("lorawan_version")
		x.LorawanVersion.MarshalProtoJSON(s)
	}
	if len(x.JoinNonce) > 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("join_nonce")
		x.JoinNonce.MarshalProtoJSON(s.WithField("join_nonce"))
	}
	if len(x.DevNonce) > 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("dev_nonce")
		x.DevNonce.MarshalProtoJSON(s.WithField("dev_nonce"))
	}
	if len(x.NetId) > 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("net_id")
		x.NetId.MarshalProtoJSON(s.WithField("net_id"))
	}
	if x.ProvisionerId != "" {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("provisioner_id")
		s.WriteString(x.ProvisionerId)
	}
	if x.ProvisioningData != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("provisioning_data")
		gogo.MarshalStruct(s, x.ProvisioningData)
	}
	s.WriteObjectEnd()
}

// UnmarshalProtoJSON unmarshals the DeriveSessionKeysRequest message from JSON.
func (x *DeriveSessionKeysRequest) UnmarshalProtoJSON(s *jsonplugin.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.ReadAny() // ignore unknown field
		case "ids":
			// NOTE: EndDeviceIdentifiers does not seem to implement UnmarshalProtoJSON.
			var v EndDeviceIdentifiers
			gogo.UnmarshalMessage(s, &v)
			x.EndDeviceIdentifiers = v
		case "lorawan_version", "lorawanVersion":
			x.LorawanVersion.UnmarshalProtoJSON(s)
		case "join_nonce", "joinNonce":
			x.JoinNonce.UnmarshalProtoJSON(s.WithField("join_nonce"))
		case "dev_nonce", "devNonce":
			x.DevNonce.UnmarshalProtoJSON(s.WithField("dev_nonce"))
		case "net_id", "netId":
			x.NetId.UnmarshalProtoJSON(s.WithField("net_id"))
		case "provisioner_id", "provisionerId":
			x.ProvisionerId = s.ReadString()
		case "provisioning_data", "provisioningData":
			v := gogo.UnmarshalStruct(s)
			if s.Err() != nil {
				return
			}
			x.ProvisioningData = v
		}
	})
}
