// Code generated by protoc-gen-go-json. DO NOT EDIT.
// versions:
// - protoc-gen-go-json vmaster
// - protoc             v3.9.1
// source: lorawan-stack/api/messages.proto

package ttnpb

import (
	gogo "github.com/TheThingsIndustries/protoc-gen-go-json/gogo"
	jsonplugin "github.com/TheThingsIndustries/protoc-gen-go-json/jsonplugin"
)

// MarshalProtoJSON marshals the PayloadFormatter to JSON.
func (x PayloadFormatter) MarshalProtoJSON(s *jsonplugin.MarshalState) {
	s.WriteEnumString(int32(x), PayloadFormatter_name)
}

// PayloadFormatter_customvalue contains custom string values that extend PayloadFormatter_value.
var PayloadFormatter_customvalue = map[string]int32{
	"NONE":         0,
	"REPOSITORY":   1,
	"GRPC_SERVICE": 2,
	"JAVASCRIPT":   3,
	"CAYENNELPP":   4,
}

// UnmarshalProtoJSON unmarshals the PayloadFormatter from JSON.
func (x *PayloadFormatter) UnmarshalProtoJSON(s *jsonplugin.UnmarshalState) {
	v := s.ReadEnum(PayloadFormatter_value, PayloadFormatter_customvalue)
	if err := s.Err(); err != nil {
		s.SetErrorf("could not read PayloadFormatter enum: %v", err)
		return
	}
	*x = PayloadFormatter(v)
}

// MarshalProtoJSON marshals the UplinkMessage message to JSON.
func (x *UplinkMessage) MarshalProtoJSON(s *jsonplugin.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if len(x.RawPayload) > 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("raw_payload")
		s.WriteBytes(x.RawPayload)
	}
	if x.Payload != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("payload")
		x.Payload.MarshalProtoJSON(s.WithField("payload"))
	}
	if true { // (gogoproto.nullable) = false
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("settings")
		x.Settings.MarshalProtoJSON(s.WithField("settings"))
	}
	if len(x.RxMetadata) > 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("rx_metadata")
		s.WriteArrayStart()
		var wroteElement bool
		for _, element := range x.RxMetadata {
			s.WriteMoreIf(&wroteElement)
			element.MarshalProtoJSON(s.WithField("rx_metadata"))
		}
		s.WriteArrayEnd()
	}
	if true { // (gogoproto.nullable) = false
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("received_at")
		s.WriteTime(x.ReceivedAt)
	}
	if len(x.CorrelationIds) > 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("correlation_ids")
		s.WriteStringArray(x.CorrelationIds)
	}
	if x.DeviceChannelIndex != 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("device_channel_index")
		s.WriteUint32(x.DeviceChannelIndex)
	}
	if x.ConsumedAirtime != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("consumed_airtime")
		s.WriteDuration(*x.ConsumedAirtime)
	}
	s.WriteObjectEnd()
}

// UnmarshalProtoJSON unmarshals the UplinkMessage message from JSON.
func (x *UplinkMessage) UnmarshalProtoJSON(s *jsonplugin.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.ReadAny() // ignore unknown field
		case "raw_payload", "rawPayload":
			x.RawPayload = s.ReadBytes()
		case "payload":
			if !s.ReadNil() {
				x.Payload = &Message{}
				x.Payload.UnmarshalProtoJSON(s.WithField("payload"))
			}
		case "settings":
			if !s.ReadNil() {
				x.Settings.UnmarshalProtoJSON(s.WithField("settings"))
			}
		case "rx_metadata", "rxMetadata":
			s.ReadArray(func() {
				if !s.ReadNil() {
					v := &RxMetadata{}
					v.UnmarshalProtoJSON(s.WithField("rx_metadata"))
					x.RxMetadata = append(x.RxMetadata, v)
				} else {
					x.RxMetadata = append(x.RxMetadata, nil)
				}
			})
		case "received_at", "receivedAt":
			v := s.ReadTime()
			if s.Err() != nil {
				return
			}
			x.ReceivedAt = *v
		case "correlation_ids", "correlationIds":
			x.CorrelationIds = s.ReadStringArray()
		case "device_channel_index", "deviceChannelIndex":
			x.DeviceChannelIndex = s.ReadUint32()
		case "consumed_airtime", "consumedAirtime":
			v := s.ReadDuration()
			if s.Err() != nil {
				return
			}
			x.ConsumedAirtime = v
		}
	})
}

// MarshalProtoJSON marshals the DownlinkMessage message to JSON.
func (x *DownlinkMessage) MarshalProtoJSON(s *jsonplugin.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if len(x.RawPayload) > 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("raw_payload")
		s.WriteBytes(x.RawPayload)
	}
	if x.Payload != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("payload")
		x.Payload.MarshalProtoJSON(s.WithField("payload"))
	}
	if x.EndDeviceIds != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("end_device_ids")
		// NOTE: EndDeviceIdentifiers does not seem to implement MarshalProtoJSON.
		gogo.MarshalMessage(s, x.EndDeviceIds)
	}
	if x.Settings != nil {
		switch v := x.Settings.(type) {
		case *DownlinkMessage_Request:
			s.WriteMoreIf(&wroteField)
			s.WriteObjectField("request")
			v.Request.MarshalProtoJSON(s.WithField("request"))
		case *DownlinkMessage_Scheduled:
			s.WriteMoreIf(&wroteField)
			s.WriteObjectField("scheduled")
			v.Scheduled.MarshalProtoJSON(s.WithField("scheduled"))
		}
	}
	if len(x.CorrelationIds) > 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("correlation_ids")
		s.WriteStringArray(x.CorrelationIds)
	}
	if len(x.SessionKeyId) > 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("session_key_id")
		s.WriteBytes(x.SessionKeyId)
	}
	s.WriteObjectEnd()
}

// UnmarshalProtoJSON unmarshals the DownlinkMessage message from JSON.
func (x *DownlinkMessage) UnmarshalProtoJSON(s *jsonplugin.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.ReadAny() // ignore unknown field
		case "raw_payload", "rawPayload":
			x.RawPayload = s.ReadBytes()
		case "payload":
			if !s.ReadNil() {
				x.Payload = &Message{}
				x.Payload.UnmarshalProtoJSON(s.WithField("payload"))
			}
		case "end_device_ids", "endDeviceIds":
			// NOTE: EndDeviceIdentifiers does not seem to implement UnmarshalProtoJSON.
			var v EndDeviceIdentifiers
			gogo.UnmarshalMessage(s, &v)
			x.EndDeviceIds = &v
		case "request":
			ov := &DownlinkMessage_Request{}
			if !s.ReadNil() {
				ov.Request = &TxRequest{}
				ov.Request.UnmarshalProtoJSON(s.WithField("request"))
			}
			x.Settings = ov
		case "scheduled":
			ov := &DownlinkMessage_Scheduled{}
			if !s.ReadNil() {
				ov.Scheduled = &TxSettings{}
				ov.Scheduled.UnmarshalProtoJSON(s.WithField("scheduled"))
			}
			x.Settings = ov
		case "correlation_ids", "correlationIds":
			x.CorrelationIds = s.ReadStringArray()
		case "session_key_id", "sessionKeyId":
			x.SessionKeyId = s.ReadBytes()
		}
	})
}

// MarshalProtoJSON marshals the TxAcknowledgment_Result to JSON.
func (x TxAcknowledgment_Result) MarshalProtoJSON(s *jsonplugin.MarshalState) {
	s.WriteEnumString(int32(x), TxAcknowledgment_Result_name)
}

// UnmarshalProtoJSON unmarshals the TxAcknowledgment_Result from JSON.
func (x *TxAcknowledgment_Result) UnmarshalProtoJSON(s *jsonplugin.UnmarshalState) {
	v := s.ReadEnum(TxAcknowledgment_Result_value)
	if err := s.Err(); err != nil {
		s.SetErrorf("could not read Result enum: %v", err)
		return
	}
	*x = TxAcknowledgment_Result(v)
}

// MarshalProtoJSON marshals the TxAcknowledgment message to JSON.
func (x *TxAcknowledgment) MarshalProtoJSON(s *jsonplugin.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if len(x.CorrelationIds) > 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("correlation_ids")
		s.WriteStringArray(x.CorrelationIds)
	}
	if x.Result != 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("result")
		x.Result.MarshalProtoJSON(s)
	}
	if x.DownlinkMessage != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("downlink_message")
		x.DownlinkMessage.MarshalProtoJSON(s.WithField("downlink_message"))
	}
	s.WriteObjectEnd()
}

// UnmarshalProtoJSON unmarshals the TxAcknowledgment message from JSON.
func (x *TxAcknowledgment) UnmarshalProtoJSON(s *jsonplugin.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.ReadAny() // ignore unknown field
		case "correlation_ids", "correlationIds":
			x.CorrelationIds = s.ReadStringArray()
		case "result":
			x.Result.UnmarshalProtoJSON(s)
		case "downlink_message", "downlinkMessage":
			if !s.ReadNil() {
				x.DownlinkMessage = &DownlinkMessage{}
				x.DownlinkMessage.UnmarshalProtoJSON(s.WithField("downlink_message"))
			}
		}
	})
}

// MarshalProtoJSON marshals the GatewayTxAcknowledgment message to JSON.
func (x *GatewayTxAcknowledgment) MarshalProtoJSON(s *jsonplugin.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.GatewayIds != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("gateway_ids")
		// NOTE: GatewayIdentifiers does not seem to implement MarshalProtoJSON.
		gogo.MarshalMessage(s, x.GatewayIds)
	}
	if x.TxAck != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("tx_ack")
		x.TxAck.MarshalProtoJSON(s.WithField("tx_ack"))
	}
	s.WriteObjectEnd()
}

// UnmarshalProtoJSON unmarshals the GatewayTxAcknowledgment message from JSON.
func (x *GatewayTxAcknowledgment) UnmarshalProtoJSON(s *jsonplugin.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.ReadAny() // ignore unknown field
		case "gateway_ids", "gatewayIds":
			// NOTE: GatewayIdentifiers does not seem to implement UnmarshalProtoJSON.
			var v GatewayIdentifiers
			gogo.UnmarshalMessage(s, &v)
			x.GatewayIds = &v
		case "tx_ack", "txAck":
			if !s.ReadNil() {
				x.TxAck = &TxAcknowledgment{}
				x.TxAck.UnmarshalProtoJSON(s.WithField("tx_ack"))
			}
		}
	})
}

// MarshalProtoJSON marshals the GatewayUplinkMessage message to JSON.
func (x *GatewayUplinkMessage) MarshalProtoJSON(s *jsonplugin.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.UplinkMessage != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("message")
		x.UplinkMessage.MarshalProtoJSON(s.WithField("message"))
	}
	if x.BandId != "" {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("band_id")
		s.WriteString(x.BandId)
	}
	s.WriteObjectEnd()
}

// UnmarshalProtoJSON unmarshals the GatewayUplinkMessage message from JSON.
func (x *GatewayUplinkMessage) UnmarshalProtoJSON(s *jsonplugin.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.ReadAny() // ignore unknown field
		case "message":
			if !s.ReadNil() {
				x.UplinkMessage = &UplinkMessage{}
				x.UplinkMessage.UnmarshalProtoJSON(s.WithField("message"))
			}
		case "band_id", "bandId":
			x.BandId = s.ReadString()
		}
	})
}

// MarshalProtoJSON marshals the ApplicationUplink message to JSON.
func (x *ApplicationUplink) MarshalProtoJSON(s *jsonplugin.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if len(x.SessionKeyId) > 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("session_key_id")
		s.WriteBytes(x.SessionKeyId)
	}
	if x.FPort != 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("f_port")
		s.WriteUint32(x.FPort)
	}
	if x.FCnt != 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("f_cnt")
		s.WriteUint32(x.FCnt)
	}
	if len(x.FrmPayload) > 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("frm_payload")
		s.WriteBytes(x.FrmPayload)
	}
	if x.DecodedPayload != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("decoded_payload")
		gogo.MarshalStruct(s, x.DecodedPayload)
	}
	if len(x.DecodedPayloadWarnings) > 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("decoded_payload_warnings")
		s.WriteStringArray(x.DecodedPayloadWarnings)
	}
	if len(x.RxMetadata) > 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("rx_metadata")
		s.WriteArrayStart()
		var wroteElement bool
		for _, element := range x.RxMetadata {
			s.WriteMoreIf(&wroteElement)
			element.MarshalProtoJSON(s.WithField("rx_metadata"))
		}
		s.WriteArrayEnd()
	}
	if true { // (gogoproto.nullable) = false
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("settings")
		x.Settings.MarshalProtoJSON(s.WithField("settings"))
	}
	if true { // (gogoproto.nullable) = false
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("received_at")
		s.WriteTime(x.ReceivedAt)
	}
	if x.AppSKey != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("app_s_key")
		// NOTE: KeyEnvelope does not seem to implement MarshalProtoJSON.
		gogo.MarshalMessage(s, x.AppSKey)
	}
	if x.LastAFCntDown != 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("last_a_f_cnt_down")
		s.WriteUint32(x.LastAFCntDown)
	}
	if x.Confirmed {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("confirmed")
		s.WriteBool(x.Confirmed)
	}
	if x.ConsumedAirtime != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("consumed_airtime")
		s.WriteDuration(*x.ConsumedAirtime)
	}
	if x.Locations != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("locations")
		s.WriteObjectStart()
		var wroteElement bool
		for k, v := range x.Locations {
			s.WriteMoreIf(&wroteElement)
			s.WriteObjectStringField(k)
			v.MarshalProtoJSON(s.WithField("locations"))
		}
		s.WriteObjectEnd()
	}
	if x.VersionIds != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("version_ids")
		// NOTE: EndDeviceVersionIdentifiers does not seem to implement MarshalProtoJSON.
		gogo.MarshalMessage(s, x.VersionIds)
	}
	if x.NetworkIds != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("network_ids")
		// NOTE: NetworkIdentifiers does not seem to implement MarshalProtoJSON.
		gogo.MarshalMessage(s, x.NetworkIds)
	}
	s.WriteObjectEnd()
}

// UnmarshalProtoJSON unmarshals the ApplicationUplink message from JSON.
func (x *ApplicationUplink) UnmarshalProtoJSON(s *jsonplugin.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.ReadAny() // ignore unknown field
		case "session_key_id", "sessionKeyId":
			x.SessionKeyId = s.ReadBytes()
		case "f_port", "fPort":
			x.FPort = s.ReadUint32()
		case "f_cnt", "fCnt":
			x.FCnt = s.ReadUint32()
		case "frm_payload", "frmPayload":
			x.FrmPayload = s.ReadBytes()
		case "decoded_payload", "decodedPayload":
			v := gogo.UnmarshalStruct(s)
			if s.Err() != nil {
				return
			}
			x.DecodedPayload = v
		case "decoded_payload_warnings", "decodedPayloadWarnings":
			x.DecodedPayloadWarnings = s.ReadStringArray()
		case "rx_metadata", "rxMetadata":
			s.ReadArray(func() {
				if !s.ReadNil() {
					v := &RxMetadata{}
					v.UnmarshalProtoJSON(s.WithField("rx_metadata"))
					x.RxMetadata = append(x.RxMetadata, v)
				} else {
					x.RxMetadata = append(x.RxMetadata, nil)
				}
			})
		case "settings":
			if !s.ReadNil() {
				x.Settings.UnmarshalProtoJSON(s.WithField("settings"))
			}
		case "received_at", "receivedAt":
			v := s.ReadTime()
			if s.Err() != nil {
				return
			}
			x.ReceivedAt = *v
		case "app_s_key", "appSKey":
			// NOTE: KeyEnvelope does not seem to implement UnmarshalProtoJSON.
			var v KeyEnvelope
			gogo.UnmarshalMessage(s, &v)
			x.AppSKey = &v
		case "last_a_f_cnt_down", "lastAFCntDown":
			x.LastAFCntDown = s.ReadUint32()
		case "confirmed":
			x.Confirmed = s.ReadBool()
		case "consumed_airtime", "consumedAirtime":
			v := s.ReadDuration()
			if s.Err() != nil {
				return
			}
			x.ConsumedAirtime = v
		case "locations":
			x.Locations = make(map[string]*Location)
			s.ReadStringMap(func(key string) {
				var v Location
				v.UnmarshalProtoJSON(s)
				x.Locations[key] = &v
			})
		case "version_ids", "versionIds":
			// NOTE: EndDeviceVersionIdentifiers does not seem to implement UnmarshalProtoJSON.
			var v EndDeviceVersionIdentifiers
			gogo.UnmarshalMessage(s, &v)
			x.VersionIds = &v
		case "network_ids", "networkIds":
			// NOTE: NetworkIdentifiers does not seem to implement UnmarshalProtoJSON.
			var v NetworkIdentifiers
			gogo.UnmarshalMessage(s, &v)
			x.NetworkIds = &v
		}
	})
}

// MarshalProtoJSON marshals the ApplicationLocation message to JSON.
func (x *ApplicationLocation) MarshalProtoJSON(s *jsonplugin.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Service != "" {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("service")
		s.WriteString(x.Service)
	}
	if true { // (gogoproto.nullable) = false
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("location")
		x.Location.MarshalProtoJSON(s.WithField("location"))
	}
	if x.Attributes != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("attributes")
		s.WriteObjectStart()
		var wroteElement bool
		for k, v := range x.Attributes {
			s.WriteMoreIf(&wroteElement)
			s.WriteObjectStringField(k)
			s.WriteString(v)
		}
		s.WriteObjectEnd()
	}
	s.WriteObjectEnd()
}

// UnmarshalProtoJSON unmarshals the ApplicationLocation message from JSON.
func (x *ApplicationLocation) UnmarshalProtoJSON(s *jsonplugin.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.ReadAny() // ignore unknown field
		case "service":
			x.Service = s.ReadString()
		case "location":
			if !s.ReadNil() {
				x.Location.UnmarshalProtoJSON(s.WithField("location"))
			}
		case "attributes":
			x.Attributes = make(map[string]string)
			s.ReadStringMap(func(key string) {
				x.Attributes[key] = s.ReadString()
			})
		}
	})
}

// MarshalProtoJSON marshals the ApplicationJoinAccept message to JSON.
func (x *ApplicationJoinAccept) MarshalProtoJSON(s *jsonplugin.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if len(x.SessionKeyId) > 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("session_key_id")
		s.WriteBytes(x.SessionKeyId)
	}
	if x.AppSKey != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("app_s_key")
		// NOTE: KeyEnvelope does not seem to implement MarshalProtoJSON.
		gogo.MarshalMessage(s, x.AppSKey)
	}
	if len(x.InvalidatedDownlinks) > 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("invalidated_downlinks")
		s.WriteArrayStart()
		var wroteElement bool
		for _, element := range x.InvalidatedDownlinks {
			s.WriteMoreIf(&wroteElement)
			element.MarshalProtoJSON(s.WithField("invalidated_downlinks"))
		}
		s.WriteArrayEnd()
	}
	if x.PendingSession {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("pending_session")
		s.WriteBool(x.PendingSession)
	}
	if true { // (gogoproto.nullable) = false
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("received_at")
		s.WriteTime(x.ReceivedAt)
	}
	s.WriteObjectEnd()
}

// UnmarshalProtoJSON unmarshals the ApplicationJoinAccept message from JSON.
func (x *ApplicationJoinAccept) UnmarshalProtoJSON(s *jsonplugin.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.ReadAny() // ignore unknown field
		case "session_key_id", "sessionKeyId":
			x.SessionKeyId = s.ReadBytes()
		case "app_s_key", "appSKey":
			// NOTE: KeyEnvelope does not seem to implement UnmarshalProtoJSON.
			var v KeyEnvelope
			gogo.UnmarshalMessage(s, &v)
			x.AppSKey = &v
		case "invalidated_downlinks", "invalidatedDownlinks":
			s.ReadArray(func() {
				if !s.ReadNil() {
					v := &ApplicationDownlink{}
					v.UnmarshalProtoJSON(s.WithField("invalidated_downlinks"))
					x.InvalidatedDownlinks = append(x.InvalidatedDownlinks, v)
				} else {
					x.InvalidatedDownlinks = append(x.InvalidatedDownlinks, nil)
				}
			})
		case "pending_session", "pendingSession":
			x.PendingSession = s.ReadBool()
		case "received_at", "receivedAt":
			v := s.ReadTime()
			if s.Err() != nil {
				return
			}
			x.ReceivedAt = *v
		}
	})
}

// MarshalProtoJSON marshals the ApplicationDownlink message to JSON.
func (x *ApplicationDownlink) MarshalProtoJSON(s *jsonplugin.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if len(x.SessionKeyId) > 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("session_key_id")
		s.WriteBytes(x.SessionKeyId)
	}
	if x.FPort != 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("f_port")
		s.WriteUint32(x.FPort)
	}
	if x.FCnt != 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("f_cnt")
		s.WriteUint32(x.FCnt)
	}
	if len(x.FrmPayload) > 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("frm_payload")
		s.WriteBytes(x.FrmPayload)
	}
	if x.DecodedPayload != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("decoded_payload")
		gogo.MarshalStruct(s, x.DecodedPayload)
	}
	if len(x.DecodedPayloadWarnings) > 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("decoded_payload_warnings")
		s.WriteStringArray(x.DecodedPayloadWarnings)
	}
	if x.Confirmed {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("confirmed")
		s.WriteBool(x.Confirmed)
	}
	if x.ClassBC != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("class_b_c")
		// NOTE: ApplicationDownlink_ClassBC does not seem to implement MarshalProtoJSON.
		gogo.MarshalMessage(s, x.ClassBC)
	}
	if x.Priority != 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("priority")
		x.Priority.MarshalProtoJSON(s)
	}
	if len(x.CorrelationIds) > 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("correlation_ids")
		s.WriteStringArray(x.CorrelationIds)
	}
	s.WriteObjectEnd()
}

// UnmarshalProtoJSON unmarshals the ApplicationDownlink message from JSON.
func (x *ApplicationDownlink) UnmarshalProtoJSON(s *jsonplugin.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.ReadAny() // ignore unknown field
		case "session_key_id", "sessionKeyId":
			x.SessionKeyId = s.ReadBytes()
		case "f_port", "fPort":
			x.FPort = s.ReadUint32()
		case "f_cnt", "fCnt":
			x.FCnt = s.ReadUint32()
		case "frm_payload", "frmPayload":
			x.FrmPayload = s.ReadBytes()
		case "decoded_payload", "decodedPayload":
			v := gogo.UnmarshalStruct(s)
			if s.Err() != nil {
				return
			}
			x.DecodedPayload = v
		case "decoded_payload_warnings", "decodedPayloadWarnings":
			x.DecodedPayloadWarnings = s.ReadStringArray()
		case "confirmed":
			x.Confirmed = s.ReadBool()
		case "class_b_c", "classBC":
			// NOTE: ApplicationDownlink_ClassBC does not seem to implement UnmarshalProtoJSON.
			var v ApplicationDownlink_ClassBC
			gogo.UnmarshalMessage(s, &v)
			x.ClassBC = &v
		case "priority":
			x.Priority.UnmarshalProtoJSON(s)
		case "correlation_ids", "correlationIds":
			x.CorrelationIds = s.ReadStringArray()
		}
	})
}

// MarshalProtoJSON marshals the ApplicationDownlinks message to JSON.
func (x *ApplicationDownlinks) MarshalProtoJSON(s *jsonplugin.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if len(x.Downlinks) > 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("downlinks")
		s.WriteArrayStart()
		var wroteElement bool
		for _, element := range x.Downlinks {
			s.WriteMoreIf(&wroteElement)
			element.MarshalProtoJSON(s.WithField("downlinks"))
		}
		s.WriteArrayEnd()
	}
	s.WriteObjectEnd()
}

// UnmarshalProtoJSON unmarshals the ApplicationDownlinks message from JSON.
func (x *ApplicationDownlinks) UnmarshalProtoJSON(s *jsonplugin.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.ReadAny() // ignore unknown field
		case "downlinks":
			s.ReadArray(func() {
				if !s.ReadNil() {
					v := &ApplicationDownlink{}
					v.UnmarshalProtoJSON(s.WithField("downlinks"))
					x.Downlinks = append(x.Downlinks, v)
				} else {
					x.Downlinks = append(x.Downlinks, nil)
				}
			})
		}
	})
}

// MarshalProtoJSON marshals the ApplicationDownlinkFailed message to JSON.
func (x *ApplicationDownlinkFailed) MarshalProtoJSON(s *jsonplugin.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if true { // (gogoproto.nullable) = false
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("downlink")
		x.ApplicationDownlink.MarshalProtoJSON(s.WithField("downlink"))
	}
	if true { // (gogoproto.nullable) = false
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("error")
		// NOTE: ErrorDetails does not seem to implement MarshalProtoJSON.
		gogo.MarshalMessage(s, &x.Error)
	}
	s.WriteObjectEnd()
}

// UnmarshalProtoJSON unmarshals the ApplicationDownlinkFailed message from JSON.
func (x *ApplicationDownlinkFailed) UnmarshalProtoJSON(s *jsonplugin.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.ReadAny() // ignore unknown field
		case "downlink":
			if !s.ReadNil() {
				x.ApplicationDownlink.UnmarshalProtoJSON(s.WithField("downlink"))
			}
		case "error":
			// NOTE: ErrorDetails does not seem to implement UnmarshalProtoJSON.
			var v ErrorDetails
			gogo.UnmarshalMessage(s, &v)
			x.Error = v
		}
	})
}

// MarshalProtoJSON marshals the ApplicationInvalidatedDownlinks message to JSON.
func (x *ApplicationInvalidatedDownlinks) MarshalProtoJSON(s *jsonplugin.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if len(x.Downlinks) > 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("downlinks")
		s.WriteArrayStart()
		var wroteElement bool
		for _, element := range x.Downlinks {
			s.WriteMoreIf(&wroteElement)
			element.MarshalProtoJSON(s.WithField("downlinks"))
		}
		s.WriteArrayEnd()
	}
	if x.LastFCntDown != 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("last_f_cnt_down")
		s.WriteUint32(x.LastFCntDown)
	}
	if len(x.SessionKeyId) > 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("session_key_id")
		s.WriteBytes(x.SessionKeyId)
	}
	s.WriteObjectEnd()
}

// UnmarshalProtoJSON unmarshals the ApplicationInvalidatedDownlinks message from JSON.
func (x *ApplicationInvalidatedDownlinks) UnmarshalProtoJSON(s *jsonplugin.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.ReadAny() // ignore unknown field
		case "downlinks":
			s.ReadArray(func() {
				if !s.ReadNil() {
					v := &ApplicationDownlink{}
					v.UnmarshalProtoJSON(s.WithField("downlinks"))
					x.Downlinks = append(x.Downlinks, v)
				} else {
					x.Downlinks = append(x.Downlinks, nil)
				}
			})
		case "last_f_cnt_down", "lastFCntDown":
			x.LastFCntDown = s.ReadUint32()
		case "session_key_id", "sessionKeyId":
			x.SessionKeyId = s.ReadBytes()
		}
	})
}

// MarshalProtoJSON marshals the ApplicationUp message to JSON.
func (x *ApplicationUp) MarshalProtoJSON(s *jsonplugin.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if true { // (gogoproto.nullable) = false
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("end_device_ids")
		// NOTE: EndDeviceIdentifiers does not seem to implement MarshalProtoJSON.
		gogo.MarshalMessage(s, &x.EndDeviceIdentifiers)
	}
	if len(x.CorrelationIds) > 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("correlation_ids")
		s.WriteStringArray(x.CorrelationIds)
	}
	if x.ReceivedAt != nil {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("received_at")
		s.WriteTime(*x.ReceivedAt)
	}
	if x.Up != nil {
		switch v := x.Up.(type) {
		case *ApplicationUp_UplinkMessage:
			s.WriteMoreIf(&wroteField)
			s.WriteObjectField("uplink_message")
			v.UplinkMessage.MarshalProtoJSON(s.WithField("uplink_message"))
		case *ApplicationUp_JoinAccept:
			s.WriteMoreIf(&wroteField)
			s.WriteObjectField("join_accept")
			v.JoinAccept.MarshalProtoJSON(s.WithField("join_accept"))
		case *ApplicationUp_DownlinkAck:
			s.WriteMoreIf(&wroteField)
			s.WriteObjectField("downlink_ack")
			v.DownlinkAck.MarshalProtoJSON(s.WithField("downlink_ack"))
		case *ApplicationUp_DownlinkNack:
			s.WriteMoreIf(&wroteField)
			s.WriteObjectField("downlink_nack")
			v.DownlinkNack.MarshalProtoJSON(s.WithField("downlink_nack"))
		case *ApplicationUp_DownlinkSent:
			s.WriteMoreIf(&wroteField)
			s.WriteObjectField("downlink_sent")
			v.DownlinkSent.MarshalProtoJSON(s.WithField("downlink_sent"))
		case *ApplicationUp_DownlinkFailed:
			s.WriteMoreIf(&wroteField)
			s.WriteObjectField("downlink_failed")
			v.DownlinkFailed.MarshalProtoJSON(s.WithField("downlink_failed"))
		case *ApplicationUp_DownlinkQueued:
			s.WriteMoreIf(&wroteField)
			s.WriteObjectField("downlink_queued")
			v.DownlinkQueued.MarshalProtoJSON(s.WithField("downlink_queued"))
		case *ApplicationUp_DownlinkQueueInvalidated:
			s.WriteMoreIf(&wroteField)
			s.WriteObjectField("downlink_queue_invalidated")
			v.DownlinkQueueInvalidated.MarshalProtoJSON(s.WithField("downlink_queue_invalidated"))
		case *ApplicationUp_LocationSolved:
			s.WriteMoreIf(&wroteField)
			s.WriteObjectField("location_solved")
			v.LocationSolved.MarshalProtoJSON(s.WithField("location_solved"))
		case *ApplicationUp_ServiceData:
			s.WriteMoreIf(&wroteField)
			s.WriteObjectField("service_data")
			// NOTE: ApplicationServiceData does not seem to implement MarshalProtoJSON.
			gogo.MarshalMessage(s, v.ServiceData)
		}
	}
	if x.Simulated {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("simulated")
		s.WriteBool(x.Simulated)
	}
	s.WriteObjectEnd()
}

// UnmarshalProtoJSON unmarshals the ApplicationUp message from JSON.
func (x *ApplicationUp) UnmarshalProtoJSON(s *jsonplugin.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.ReadAny() // ignore unknown field
		case "end_device_ids", "endDeviceIds":
			// NOTE: EndDeviceIdentifiers does not seem to implement UnmarshalProtoJSON.
			var v EndDeviceIdentifiers
			gogo.UnmarshalMessage(s, &v)
			x.EndDeviceIdentifiers = v
		case "correlation_ids", "correlationIds":
			x.CorrelationIds = s.ReadStringArray()
		case "received_at", "receivedAt":
			v := s.ReadTime()
			if s.Err() != nil {
				return
			}
			x.ReceivedAt = v
		case "uplink_message", "uplinkMessage":
			ov := &ApplicationUp_UplinkMessage{}
			if !s.ReadNil() {
				ov.UplinkMessage = &ApplicationUplink{}
				ov.UplinkMessage.UnmarshalProtoJSON(s.WithField("uplink_message"))
			}
			x.Up = ov
		case "join_accept", "joinAccept":
			ov := &ApplicationUp_JoinAccept{}
			if !s.ReadNil() {
				ov.JoinAccept = &ApplicationJoinAccept{}
				ov.JoinAccept.UnmarshalProtoJSON(s.WithField("join_accept"))
			}
			x.Up = ov
		case "downlink_ack", "downlinkAck":
			ov := &ApplicationUp_DownlinkAck{}
			if !s.ReadNil() {
				ov.DownlinkAck = &ApplicationDownlink{}
				ov.DownlinkAck.UnmarshalProtoJSON(s.WithField("downlink_ack"))
			}
			x.Up = ov
		case "downlink_nack", "downlinkNack":
			ov := &ApplicationUp_DownlinkNack{}
			if !s.ReadNil() {
				ov.DownlinkNack = &ApplicationDownlink{}
				ov.DownlinkNack.UnmarshalProtoJSON(s.WithField("downlink_nack"))
			}
			x.Up = ov
		case "downlink_sent", "downlinkSent":
			ov := &ApplicationUp_DownlinkSent{}
			if !s.ReadNil() {
				ov.DownlinkSent = &ApplicationDownlink{}
				ov.DownlinkSent.UnmarshalProtoJSON(s.WithField("downlink_sent"))
			}
			x.Up = ov
		case "downlink_failed", "downlinkFailed":
			ov := &ApplicationUp_DownlinkFailed{}
			if !s.ReadNil() {
				ov.DownlinkFailed = &ApplicationDownlinkFailed{}
				ov.DownlinkFailed.UnmarshalProtoJSON(s.WithField("downlink_failed"))
			}
			x.Up = ov
		case "downlink_queued", "downlinkQueued":
			ov := &ApplicationUp_DownlinkQueued{}
			if !s.ReadNil() {
				ov.DownlinkQueued = &ApplicationDownlink{}
				ov.DownlinkQueued.UnmarshalProtoJSON(s.WithField("downlink_queued"))
			}
			x.Up = ov
		case "downlink_queue_invalidated", "downlinkQueueInvalidated":
			ov := &ApplicationUp_DownlinkQueueInvalidated{}
			if !s.ReadNil() {
				ov.DownlinkQueueInvalidated = &ApplicationInvalidatedDownlinks{}
				ov.DownlinkQueueInvalidated.UnmarshalProtoJSON(s.WithField("downlink_queue_invalidated"))
			}
			x.Up = ov
		case "location_solved", "locationSolved":
			ov := &ApplicationUp_LocationSolved{}
			if !s.ReadNil() {
				ov.LocationSolved = &ApplicationLocation{}
				ov.LocationSolved.UnmarshalProtoJSON(s.WithField("location_solved"))
			}
			x.Up = ov
		case "service_data", "serviceData":
			ov := &ApplicationUp_ServiceData{}
			// NOTE: ApplicationServiceData does not seem to implement UnmarshalProtoJSON.
			var v ApplicationServiceData
			gogo.UnmarshalMessage(s, &v)
			ov.ServiceData = &v
			x.Up = ov
		case "simulated":
			x.Simulated = s.ReadBool()
		}
	})
}

// MarshalProtoJSON marshals the MessagePayloadFormatters message to JSON.
func (x *MessagePayloadFormatters) MarshalProtoJSON(s *jsonplugin.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.UpFormatter != 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("up_formatter")
		x.UpFormatter.MarshalProtoJSON(s)
	}
	if x.UpFormatterParameter != "" {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("up_formatter_parameter")
		s.WriteString(x.UpFormatterParameter)
	}
	if x.DownFormatter != 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("down_formatter")
		x.DownFormatter.MarshalProtoJSON(s)
	}
	if x.DownFormatterParameter != "" {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("down_formatter_parameter")
		s.WriteString(x.DownFormatterParameter)
	}
	s.WriteObjectEnd()
}

// UnmarshalProtoJSON unmarshals the MessagePayloadFormatters message from JSON.
func (x *MessagePayloadFormatters) UnmarshalProtoJSON(s *jsonplugin.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.ReadAny() // ignore unknown field
		case "up_formatter", "upFormatter":
			x.UpFormatter.UnmarshalProtoJSON(s)
		case "up_formatter_parameter", "upFormatterParameter":
			x.UpFormatterParameter = s.ReadString()
		case "down_formatter", "downFormatter":
			x.DownFormatter.UnmarshalProtoJSON(s)
		case "down_formatter_parameter", "downFormatterParameter":
			x.DownFormatterParameter = s.ReadString()
		}
	})
}

// MarshalProtoJSON marshals the DownlinkQueueRequest message to JSON.
func (x *DownlinkQueueRequest) MarshalProtoJSON(s *jsonplugin.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if true { // (gogoproto.nullable) = false
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("end_device_ids")
		// NOTE: EndDeviceIdentifiers does not seem to implement MarshalProtoJSON.
		gogo.MarshalMessage(s, &x.EndDeviceIdentifiers)
	}
	if len(x.Downlinks) > 0 {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("downlinks")
		s.WriteArrayStart()
		var wroteElement bool
		for _, element := range x.Downlinks {
			s.WriteMoreIf(&wroteElement)
			element.MarshalProtoJSON(s.WithField("downlinks"))
		}
		s.WriteArrayEnd()
	}
	s.WriteObjectEnd()
}

// UnmarshalProtoJSON unmarshals the DownlinkQueueRequest message from JSON.
func (x *DownlinkQueueRequest) UnmarshalProtoJSON(s *jsonplugin.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.ReadAny() // ignore unknown field
		case "end_device_ids", "endDeviceIds":
			// NOTE: EndDeviceIdentifiers does not seem to implement UnmarshalProtoJSON.
			var v EndDeviceIdentifiers
			gogo.UnmarshalMessage(s, &v)
			x.EndDeviceIdentifiers = v
		case "downlinks":
			s.ReadArray(func() {
				if !s.ReadNil() {
					v := &ApplicationDownlink{}
					v.UnmarshalProtoJSON(s.WithField("downlinks"))
					x.Downlinks = append(x.Downlinks, v)
				} else {
					x.Downlinks = append(x.Downlinks, nil)
				}
			})
		}
	})
}
